import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../services/master_data_service.dart';

class AuditLogsScreen extends StatelessWidget {
  const AuditLogsScreen({super.key});
  @override Widget build(BuildContext context)=>Scaffold(body:Stack(children:[const _Water(),SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded)),const SizedBox(width:8),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Audit Logs',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('Master actions and control changes',style:TextStyle(color:Color(0xff5F7180)))]))]),const SizedBox(height:22),Expanded(child:Card(color:Colors.white.withValues(alpha:.94),elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),child:Padding(padding:const EdgeInsets.all(18),child:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:MasterDataService.auditLogs(),builder:(context,snap){if(snap.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(snap.hasError)return Center(child:Text('Unable to load audit logs: ${snap.error}'));final docs=snap.data?.docs??[];if(docs.isEmpty)return const Center(child:Text('No audit activity yet',style:TextStyle(fontWeight:FontWeight.w700)));return ListView.separated(itemCount:docs.length,separatorBuilder:(_,__)=>const Divider(),itemBuilder:(_,i){final d=docs[i].data();final ts=d['createdAt'];final time=ts is Timestamp?ts.toDate().toLocal().toString():'Pending';return ListTile(leading:const CircleAvatar(backgroundColor:Color(0xffE1F4FF),child:Icon(Icons.fact_check_rounded,color:Color(0xff1677D2))),title:Text('${d['action']??'action'}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('Service: ${d['service']??'—'}  •  Target: ${d['targetAdminId']??d['targetInstituteId']??d['targetUid']??'—'}\n$time'));});}))))])))]));
}
class _Water extends StatelessWidget{const _Water();@override Widget build(BuildContext context)=>Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xffB8E9FF),Color(0xffF0FBFF),Color(0xff86D2F5)])));}
