import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../services/master_data_service.dart';

class ServiceManagementScreen extends StatelessWidget {
  const ServiceManagementScreen({super.key});
  static const services=<String,String>{'studentApp':'Student App','adminPanel':'Admin Panel','mockTests':'Mock Tests','liveTests':'Live Tests','questionBank':'Question Bank','currentAffairs':'Current Affairs','leaderboard':'Leaderboard','notifications':'Notifications','rewards':'Rewards'};
  @override Widget build(BuildContext context)=>Scaffold(body:Stack(children:[const _Water(),SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded)),const SizedBox(width:8),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Service Management',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('Master switches are the top-level authority',style:TextStyle(color:Color(0xff5F7180)))]))]),const SizedBox(height:22),Expanded(child:Card(color:Colors.white.withValues(alpha:.94),elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),child:Padding(padding:const EdgeInsets.all(18),child:StreamBuilder<DocumentSnapshot<Map<String,dynamic>>>(stream:MasterDataService.services(),builder:(context,snap){final data=snap.data?.data()??{};return ListView.separated(itemCount:services.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final key=services.keys.elementAt(i);final label=services[key]!;final enabled=data[key]!=false;return SwitchListTile(title:Text(label,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(enabled?'Master enabled • Admin/Student may be enabled below':'Master disabled • lower levels cannot enable this service'),value:enabled,onChanged:(v)=>MasterDataService.setMasterService(key,v),secondary:Icon(Icons.tune_rounded,color:enabled?const Color(0xff1677D2):const Color(0xff8798A6)));});}))))])))]));
}
class _Water extends StatelessWidget{const _Water();@override Widget build(BuildContext context)=>Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xffB8E9FF),Color(0xffF0FBFF),Color(0xff86D2F5)])));}
