import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../services/master_data_service.dart';

class StudentManagementScreen extends StatelessWidget {
  const StudentManagementScreen({super.key});
  @override Widget build(BuildContext context)=>Scaffold(body:Stack(children:[const _Water(),SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded)),const SizedBox(width:8),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Student Management',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('View and control students across all institutes',style:TextStyle(color:Color(0xff5F7180)))]))]),const SizedBox(height:22),Expanded(child:Card(color:Colors.white.withValues(alpha:.94),elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),child:Padding(padding:const EdgeInsets.all(18),child:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:MasterDataService.students(),builder:(context,snap){if(snap.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(snap.hasError)return Center(child:Text('Unable to load students: ${snap.error}'));final docs=snap.data?.docs??[];if(docs.isEmpty)return const Center(child:Text('No students yet',style:TextStyle(fontWeight:FontWeight.w700)));return ListView.separated(itemCount:docs.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final d=docs[i].data();final active=d['isActive']!=false;final name='${d['name']??d['fullName']??'Student'}';final userId='${d['userId']??d.id}';return ListTile(tileColor:const Color(0xffF7FBFF),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)),leading:CircleAvatar(backgroundColor:const Color(0xffE1F4FF),child:const Icon(Icons.person_rounded,color:Color(0xff1677D2))),title:Text(name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('$userId\nInstitute: ${d['tenantId']??d['instituteId']??'—'}'),trailing:Switch(value:active,onChanged:(v)=>MasterDataService.setStudentActive(d.id,v)));});}))))])))]));
}
class _Water extends StatelessWidget{const _Water();@override Widget build(BuildContext context)=>Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xffB8E9FF),Color(0xffF0FBFF),Color(0xff86D2F5)])));}
